name: countryball_maker
description: Countryball maker
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  google_mobile_ads: any
  gal: ^2.3.0
flutter:
  uses-material-design: true
